[package]
name = "yj"
version = "0.1.0"
authors = ["Tomoki Kozuru <kozuru.tty@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
getopts = "0.2"
serde_json = "1.0.64"
serde_yaml = "0.8.17"
